" Vim config file "

set nocompatible

set clipboard=unnamed

" Netrw
filetype plugin on
let g:netrw_banner=0
let g:netrw_browse_split=0
let g:netrw_altv=1
let g:netrw_liststyle=3
let g:netrw_list_hide=netrw_gitignore#Hide()

" Autocomplete
set completeopt=menuone
set complete=.,w,b,u,t
inoremap <expr> <CR> pumvisible() ? "\<C-Y>" : "\<CR>"
function! InsertTabWrapper()
   let col = col('.') - 1
   if !col || getline('.')[col - 1] !~ '\k'
       return "\<tab>"
   else
       return "\<c-n>"
   endif
endfunction
inoremap <tab> <c-r>=InsertTabWrapper()<cr>

" Appearance
syntax on
colorscheme vs2019dark

" Disable beeping and blinking
set noeb vb t_vb=
autocmd GUIEnter * set vb t_vb=

" Show non printing characters
set listchars=eol:¬,tab:>\ ,trail:~,extends:>,precedes:<,space:·,nbsp:_

" Editor settings
set cursorline
set ignorecase
set incsearch
set hlsearch
set nowrap
set number
set list

" Status line
set laststatus=2
set statusline=
set statusline+=%f\ "
set statusline+=%r
set statusline+=%m
set statusline+=%=
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\ %11{&fileformat}
set statusline+=\ %11l,%-11c
set statusline+=\ %P

" Indentation settings
set autoindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Linebreak setting
set iskeyword=@,48-57,_,192-255
set linebreak
set display=lastline

" Menu
set path+=**
set showcmd
set wildmenu
set wildmode=list:longest,full

" Remove trailing whitespaces
autocmd BufWritePre * :%s/\s\+$//e

" Highlight overlength lines
highlight OverLength ctermfg=red guifg=red
match OverLength /\%120v.*/

" Disable mouse
set mouse=

" Split
set splitbelow
set splitright

" C++ highlight
let g:cpp_member_variable_highlight = 1
let g:cpp_class_decl_highlight = 1
let g:cpp_posix_standard = 1
let g:cpp_experimental_template_highlight = 1
let c_no_curly_error=1
