" Vim config file "

" Plugins
set rtp+=~/.vim/bundle/YouCompleteMe
set rtp+=~/.vim/bundle/nerdtree

" NERDTree
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
let g:NERDTreeDirArrowExpandable = '+'
let g:NERDTreeDirArrowCollapsible = '-'

" Close vim if only NERDTree is opened
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" YouCompleteMe
let g:ycm_min_num_of_chars_for_completion = 1
let g:ycm_enable_diagnostic_highlighting = 1
let g:ycm_enable_diagnostic_signs = 0
let g:ycm_key_list_stop_completion = ['<C-y>', '<Enter>']
let g:ycm_confirm_extra_conf = 0

set completeopt=menuone

" Appearance
syntax on
colorscheme default
set cursorline

highlight Pmenu ctermbg=lightgrey ctermfg=darkgrey
highlight PmenuSbar ctermbg=lightgrey ctermfg=darkgrey
highlight PmenuSel ctermbg=grey ctermfg=white
highlight PmenuThumb ctermbg=grey ctermfg=white

highlight NonText ctermfg=grey
highlight SpecialKey ctermfg=grey

highlight CursorLine cterm=NONE ctermbg=lightgrey ctermfg=NONE

highlight VertSplit ctermfg=white ctermbg=darkgrey

highlight StatusLine ctermfg=grey ctermbg=white
highlight StatusLineNC ctermfg=grey ctermbg=white

highlight TabLineFill ctermfg=grey ctermbg=grey
highlight TabLine ctermfg=white ctermbg=grey cterm=NONE
highlight TabLineSel ctermfg=grey ctermbg=white cterm=NONE

" GUI settings
if has("gui_running")
    set guioptions=m
    set guifont=Ubuntu\ Mono\ 12
    set lines=40
    set columns=80
endif

" Disable beeping and blinking
set noeb vb t_vb=
autocmd GUIEnter * set vb t_vb=

" Show non printing characters
" set listchars=eol:¬,tab:>\ ,trail:~,extends:>,precedes:<,space:·
set listchars=tab:>\ ,trail:~,extends:>,precedes:<,space:·

" Editor settings
set ignorecase
set incsearch
set number
set list

" Indentation settings
set autoindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Linebreak setting
set iskeyword=@,48-57,_,192-255
set linebreak
set dy=lastline

" Wildmenu
set wildmenu
set wildmode=list:longest,full

" Remove trailing whitespaces
autocmd BufWritePre * :%s/\s\+$//e

" Highlight tasm syntax
au BufRead,BufNewFile *.ASM set filetype=tasm

" Highlight overlength lines
highlight OverLength ctermfg=red guifg=red
match OverLength /\%120v.*/

" Split
set splitbelow
set splitright

" Split navigation keys
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Middle mouse button behaviour
set mouse=a
map <S-Insert> <MiddleMouse>
map! <S-Insert> <MiddleMouse>

" Map F12 to toggle tree
imap <F12> <Esc>:NERDTreeToggle<CR>
map <F12> <Esc>:NERDTreeToggle<CR>

" Map F2 to go to previous tab
imap <F2> <Esc>:tabprev<CR>
map <F2> <Esc>:tabprev<CR>

" Map F3 to go to next tab
imap <F3> <Esc>:tabnext<CR>
map <F3> <Esc>:tabnext<CR>

" Map F4 to open new tab
imap <F4> <Esc>:tabnew<CR>
map <F4> <Esc>:tabnew<CR>

" Map F5 to compile project
imap <F5> <Esc>:!./build/ya<CR>
map <F5> <Esc>:!./build/ya<CR>

" Map F6 to run project
imap <F6> <Esc>:!./ninja.sh<CR>
map <F6> <Esc>:!./ninja.sh<CR>

" Auto close brackets
inoremap " ""<left>
inoremap ' ''<left>
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O
