#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

#if ! ps ax | grep -v grep | grep statusbar; then
#	sh .statusbar
#fi

#export GTK_MODULES=topmenu-gtk-module

xrdb -merge ~/.Xresources &
xset r rate 200 40 &
feh --bg-scale wallpapers/lowpoly-rocket.png &
exec i3
