#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

#if ! ps ax | grep -v grep | grep statusbar; then
#	sh .statusbar
#fi

xrdb -merge ~/.Xresources &
xset r rate 200 50 &
feh --bg-scale wallpapers/1451945224975.jpg &
compton -cbG --shadow-exclude 'i:e:dmenu' &
exec i3
